catalog/urls.py
from django.urls import re_path,path
from .views import *

#Website urls
app_name = "catalog"

urlpatterns = [
    path('',katalog, name="katalog"),
    path('saran_katalog',saran, name="saran"),
    path('check/<cari>',check),
    path('location/<cari>',location),
    path('category/<cari>',category),
    path('all',all_show),
    path('collect_saran',collect_saran),
    path('api',api)
]

maupromosi/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

"""This urls is temporary, further action is needed"""
urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('homepage.urls')),
    re_path(r'catalog/', include('catalog.urls')),
    re_path(r'post_details/', include('postdetails.urls')),
    re_path(r'user_profile/', include('userprofile.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from maupromosi.settings import AUTH_USER_MODEL as User

class Saran(models.Model):
    saran = models.CharField(max_length=100)

class Visitor(models.Model):
    visit = models.IntegerField(default=0, null=True, blank=True)

catalog/forms.py
from django import forms
from .models import Saran

class Input_saran(forms.ModelForm):
    
    class Meta:
        model = Saran
        fields = ['saran']
        widgets={
            'saran':forms.TextInput(attrs={
                'id':'saran',
                'required':True,
                'placeholder':'Saran...'
            })
        }

catalog/views.py
from django.shortcuts import render
from postdetails.models import Post, PostLocation, PostCategory, PostReview
from .models import Visitor,Saran
from .forms import Input_saran
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse,JsonResponse
import json

# Create your views here.

def filter(request):
    db = Post.objects.all()
    nama_produk = request.GET.get("cari_produk")
    lokasi = request.GET.get("lokasi")
    kategori = request.GET.get("kategori")

    if is_valid_queryparam(nama_produk):
        if(db.filter(description__icontains = nama_produk)!= None ):
            db = db.filter(description__icontains = nama_produk)
                
    if is_valid_queryparam(lokasi):
        db = db.filter(location__location = lokasi)
    if is_valid_queryparam(kategori):
        db = db.filter(category__category = kategori)

    return db

def katalog(request):
    filtering = filter(request)
    visit = Visitor.objects.all()
    lokasi = PostLocation.objects.all()
    kategori = PostCategory.objects.all()
    count = request.session.get('count',0)
    newcount = count+1
    request.session['count'] = newcount
    visit.visit = newcount
    
    form = Input_saran()
    isi=collect_saran(request)

    context ={
        'post' : filtering,
        'visit': visit.visit,
        'lokasi' : lokasi,
        'kategori' : kategori,
        'form' : form
    }
    return render(request,'catalog/katalog.html', context)

def is_valid_queryparam(param):
    return param != '' and param is not None

def collect_saran(request):
    if request.method == 'POST':
        saran_text = request.POST.get('saran')
        response_data={}
        
        
        response_data['saran'] = saran_text

        Saran.objects.create(
            saran = saran_text
        )
        return JsonResponse(response_data)

def saran(request):
    saran = Saran.objects.all()
    content = {"saran" : saran }
    response_data = {}
    
    return render(request,'catalog/saran_katalog.html',content)

def check(request,cari):
    posts = Post.objects.filter(description__icontains=cari)
    
    return api(posts)

def location(request,cari):
    posts = Post.objects.filter(location__location=cari)
    
    return api(posts)

def category(request,cari):
    posts = Post.objects.filter(category__category=cari)
    return api(posts)

def all_show(request):
    posts = Post.objects.all()
    return api(posts)

def api(request):
    posts = request
    response = []
    for post in posts:
        if not post.location.all() or not post.category.all():
            location = ''
            category = ''
        else:
            location = ''
            category = ''
            for lokasi in post.location.all():
                if(location!=''):
                   location +=',' 
                location += lokasi.location
            for kategori in post.category.all():
                if(category!=''):
                   category +=',' 
                category += kategori.category                

        if(not post.image):
            image = ''
        else:
            image = post.image.url
        tmp = {
            'name': post.name,
            'image':image,
            'location':location,
            'category' : category,
            'description' : post.description,
            'pk':post.pk
        }
        response.append(tmp)
        
    reviews = JsonResponse({'fields':response})
    
    return reviews

templates/catalog/katalog.html
{% extends 'base.html' %}
{% load static %}
{% block head %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'catalog-js.js' %}"></script>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'katalog.css' %}"/>
    <title>MauPromosi | Katalog</title>
{% endblock %}
{% block body %}
    <div class="container">
        <h1 class="judul">Katalog Produk</h1>
        <div class="search-bar">  
          <div class="search-container">
            <form action="" method="GET" >
                <div>
                  <input class="search" type="text" placeholder="Search.." name="cari_produk" id="cari">
                  <button type="submit" class="search-btn"><i class="fa fa-search"></i></button>
                </div>        
            </form> 
          </div>
          <div class="dropdown" id="btn-lokasi">          
            <input class="dropbtn" name="lokasi" type="button"value="Lokasi">
          </div> 
          <div class="dropdown" id="btn-kategori">          
            <button class="dropbtn">Kategori</button>       
          </div>  
        </div>
        <div class="dropdown-content" id="lokasi">                
          <form action="" method="GET">
          {% for nama_lokasi in lokasi %}
          <input id="nama_lokasi"name="lokasi" value="{{ nama_lokasi }}"type="button" class="button">
          {% endfor %}              
          </form>
        </div>
        <div class="dropdown-content" id="kategori">    
          <form action="" method="GET">
          {% for nama_kategori in kategori %}
          <button id="nama_kategori"name="kategori" value="{{ nama_kategori }}"type="button" class="button">{{ nama_kategori }}</button>
          {% endfor %}
          </form>  
        </div>
        <div class="cards" id="cards">
        
        </div>
        {% if user.is_authenticated %}
        <div class="tambahan">
           <div class="pengunjung"><p style="font-size: 17px;">Anda telah mengunjungi halaman ini sebanyak {{ visit }} kali</p></div>
           <div class="saran"style="font-size: 17px;">
            <h5>Saran untuk page ini</h5>
            <form method="POST" id="saran">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            <a href="{% url 'catalog:saran' %}" ><button type="submit" class="btn btn-primary"style="margin-top: 30px;">Lihat saran page catalog</button></a>
          </div>
        </div>
        {% endif %}
    </div>
{% endblock %}

templates/catalog/saran_katalog.html
{% extends 'base.html' %}
{% load static %}
{% block head %}

<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'saran.css' %}"/>
    <title>MauPromosi | Katalog</title>

{% endblock %}

{% block body %}

<div class='container'>
    <h1>Kumpulan Saran Catalog</h1>
    {% if saran %}
    <table id="saran">
        <tr>
            <th style="width: 70px;">No</th>
            <th style="width: 1000px;text-align: center;">Saran</th>
        </tr>
        {% for saran in saran %}
        <tr>
            <td>{{ saran.id }}</td>
            <td>{{ saran.saran }}</td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <h2>Belum ada saran</h2>
    {% endif %}

    <a href="{% url 'catalog:katalog' %}"><button type="submit" class="btn-secondary">Kembali</button></a>
</div>

{% endblock %}